### ISSUE TITLE
Docs link gives a 404

### ISSUE THREAD

**Issue by ewels** [rawgraphs/rawgraphs-core#66]
Hi there!

I was looking for the docs for rawgraphs-core but the URL on the [GitHub repo](https://github.com/rawgraphs/rawgraphs-core):

<img width="308" alt="image" src="https://user-images.githubusercontent.com/465550/208121355-697571bb-9feb-45f5-b302-b0877a8f4262.png">

..and [rawgraphs docs](https://www.rawgraphs.io/documentation) page:

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/465550/208121418-77d47f6b-b59d-4171-831b-8534e6ce1cfc.png">

Both give a 404 - page not found - error. The URL is https://www.rawgraphs.io/rawgraphs-core/docs

<img width="590" alt="image" src="https://user-images.githubusercontent.com/465550/208121640-aad0d48a-2fdc-4871-b56e-da99cef6362f.png">

Thought you might like to know in case this is accidental.

Cheers,

Phil

**Comment by mikima** [comment]
Fixed by @giorgiouboldi , the new link is https://rawgraphs.github.io/rawgraphs-core/docs/
